steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args:
      - 'build'
      - '-t'
      - 'australia-southeast1-docker.pkg.dev/moveify-app/cloud-run-source-deploy/moveify-api'
      - '.'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'australia-southeast1-docker.pkg.dev/moveify-app/cloud-run-source-deploy/moveify-api'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'moveify-api'
      - '--image'
      - 'australia-southeast1-docker.pkg.dev/moveify-app/cloud-run-source-deploy/moveify-api'
      - '--region'
      - 'australia-southeast1'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'australia-southeast1-docker.pkg.dev/moveify-app/cloud-run-source-deploy/moveify-api'
